### PR TITLE
Fix #19

### LINKED ISSUE #19: [TEAM][Priority: 5][Library: wslpy.system] Distro detection
Ref: https://github.com/wslutilities/wslu/blob/221e85457c01e92db675cc7b24a49dfcdfacc6a9/src/wslu-header#L240-L257

### PR DESCRIPTION
**Pull request by shubhsboson**

### CODE REVIEW

**Review by patrick330602 — CHANGES_REQUESTED** [review]
Several issues here:
1. You should use the native python features like `open()` to handle the string instead of calling the command, these commands like `head` will be distro-independent (some come from `busybox` and others come from `core-utils` and they have the possibility of having different output) and should be avoid doing so at all time;
2. You should handle Fedora distros properly. Old versions of Fedora Remix will return `Generic` for distro and for it you should also check for `ID_LIKE=`.
3. I am expecting the same output as the reference code, for easier referring cross-project.

**Comment by shubhsboson** [comment]
I don't understand aren't we already using subprocess in say exec.py ,  system.py ?

**Comment by patrick330602** [comment]
> I don't understand aren't we already using subprocess in say exec.py , system.py ?

This is because `exec.py` is used to execute Windows command, thus the use of `subprocess`; If you read `system.py` carefully, using `subprocess` is the same reason as `exec.py`. And that's also why we build `wslpy`.

For example here:
https://github.com/wslutilities/wslpy/blob/e382b797c8cb7e5fe211a44f74ac4fa2bbd3704b/wslpy/system.py#L6-L19

you can see before line 11, `subprocess` is used, since it is executing a **Windows** command to get **Windows** Registry.

Another example here:
https://github.com/wslutilities/wslpy/blob/e382b797c8cb7e5fe211a44f74ac4fa2bbd3704b/wslpy/__init__.py#L6-L14

This reads the native Linux files and we are not using any `subprocess`.

**Comment by shubhsboson** [comment]
Is this okay ?

**Comment by shubhsboson** [comment]
Also before you mention the exception part , 
There are two probable exceptions here
1. File not found
2. No such Attribute
Now for both of these I couldn't think of a way to handle them , 
if the file isn't found what are you doing for that in bash version of this ?
Also for the exception raised in internal method , If that ever happens (which it is less likely to be)
again is there any work around ? I don't think so.

**Comment by patrick330602** [comment]
> Is this okay ?

Looks good, also some modifications needed and I will explain with your question.

> Also before you mention the exception part ,
> There are two probable exceptions here
> 
> 1. File not found
> 2. No such Attribute
>    Now for both of these I couldn't think of a way to handle them ,
>    if the file isn't found what are you doing for that in bash version of this ?
>    Also for the exception raised in internal method , If that ever happens (which it is less likely to be)
>    again is there any work around ? I don't think so.

For both cases, do not throw an error; both cases should return the distro name as `unknown`.

So for `__read_attribute__(file,attr)`, you can wrap them in Try-Except and in Except return `unknown`.

**Comment by shubhsboson** [comment]
what I think is we should leave the exceptions as is , cause form where I see it in 99.99% of cases it will
never throw an exception and if it ever does , the user will see an exception and create an issue , so we will know.
Otherwise we will never know if it's standard output or error.

**Comment by patrick330602** [comment]
That's acceptable. I see no further issues and I think this will be merged.

**Comment by patrick330602** [comment]
Also can you move the file to wslpy.system (i.e., system.py)?

**Review by patrick330602 — APPROVED** [review]

**Comment by shubhsboson** [comment]
Okay , On it!

**Comment by shubhsboson** [comment]
This cool ?

**Comment by patrick330602** [comment]
Looks good, merged

**Pull request merged**
